language: objective-c
before_script: travis/before_script.sh
script: travis/script.sh
deploy:
  provider: releases
  api_key:
    secure: "IziraEzPTspfH0nZN/mYtKrm4/HyWPEN5cvg+fNU8QeUxFUedAUm2M53TKyjb/HU+aqbccTjfHTzzZYFh6I9HAXb4+MuiehR/wBsUBAMCw+t1tahj6c+6fBT54O5/nX1zv9zhQRH/g/XXiZo8+YL4rE/ecrqCcWvLTueXUssnOQ="
  file: unity_staging/openkit-unity/OpenKitUnityPlugin/SDKPackages/Gameeso-Unity-SDK.unitypackage
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: Gameeso/openkit-unity